### ISSUE TITLE
[question] Does AWS Service Broker have any relation to AWS SErvice CAtalog??

### ISSUE THREAD

**Issue by etsangsplk** [awslabs/aws-servicebroker-documentation#10]
Are they related? Can I use Service Broker to use service created under AWS Service Catalog?
If so, how can I do it or do you know an example?

**Comment by jaymccon** [comment]
There is no relationship to AWS Service Catalog aside from that we also use CloudFormation templates to manage AWS resources. While AWS Service Catalog provides a great way to granularly control and manage the usage of a portfolio of products using the AWS console and API's, the AWS Service Broker is an Open Service Broker compliant integration for AWS Services into Application Platforms like Openshift and Kubernetes.
