### ISSUE TITLE
Can you clarify production deployment?

### ISSUE THREAD

**Issue by e-goldberg** [awslabs/aws-servicebroker-documentation#2]
Hi,
On the service broker getting-started page it says this 
Production
•	Only way to run with on-premises multi-node OpenShift cluster
I am wondering what "on-premises" means? That it can’t be deployed with OCP cluster on AWS, just on-premise? Can you help to clarify this?

**Comment by jwmatthews** [comment]
@e-goldberg we likely need to clean up the docs.

The basic concept is if you have an OCP 3.7 cluster with Service Catalog installed and you are the Administrator of the cluster and your AWS account....then you can deploy the AWS Service Broker.

The OCP cluster may be running in AWS infrastructure, or it could be running on-premise in your infrastructure, or even in a VM for evaluation purposes.  

If you can see AWS services from the OpenShift cluster (you have network access and are not blocked behind a proxy, etc) then you can run the AWS Broker.

**Comment by e-goldberg** [comment]
Thanks!
