### ISSUE TITLE
Support for pure kubernetes?

### ISSUE THREAD

**Issue by ttripp** [awslabs/aws-servicebroker-documentation#5]
Does this only work with OpenShift?  Will it work with pure Kubernetes?  Are there plans for it to work with Kubernetes?

**Comment by rniksch** [comment]
At this stage it requires OpenShift, native Kubernetes support is on the road map.

**Comment by jaymccon** [comment]
see https://github.com/awslabs/aws-servicebroker/blob/master/docs/getting-started-k8s.md for guidance on setting up in k8s
