### ISSUE TITLE
tail -n 1 fails

### ISSUE THREAD

**Issue by antoniogallegosaez** [awslabs/aws-servicebroker-documentation#6]
Running on OCP3.7onAWS the command 
_oc get secret -n kube-service-catalog -o go-template='{{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}' | tail -n 1_
fails

Had to adjust to 
_oc get secret -n kube-service-catalog -o go-template='{{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}' | tail -n 2_

to make the script to run successfully.

**Comment by johnkim76** [comment]
@antoniogallegosaez could I see what the output is with just 'tail -n 1'?  I was not able to duplicate the issue

**Comment by jaymccon** [comment]
I managed to replicate using the latest [aws openshift quickstart](https://github.com/aws-quickstart/quickstart-redhat-openshift/tree/master) and have updated the script with:

```bash
BROKER_CA_CERT=`oc get secret -n kube-service-catalog -o go-template='{{ range .items }}{{ if eq .type "kubernetes.io/service-account-token" }}{{ index .data "service-ca.crt" }}{{end}}{{"\n"}}{{end}}' | awk NF | tail -n 1`
```
